version: '3.4'

services:
  sveltedocker:
    image: sveltedocker
    build:
      context: svelte-docker
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
